---
- name: copy my index.html file
  copy: src=files/index.html dest=/var/www/html
  notify:
  - restart apache

# here we are using notify because we are doing the changes in httpd, so we need to restart the apache, and for this we are using the notify
