---
- hosts: all
  become: true
  become_user: root
  tasks:
  - name: Prints various Ansible facts
    debug:
     msg: >
       The deafult IPv4 address of {{ ansible_fqdn }} is {{ ansible_default_ipv4.address }}

# here ansible_fqdn is ansible fact that let you to know hostname of all managed host
# ansible_default_ipv4.address is also a fact that let you know the ip address
