---
- hosts: all
  become: true
  become_user: root
  tasks:
  - name: Restart Apache HTTPD if OS is RedHat & Version 7
    service:
     name: httpd
     state: restarted
    when: ansible_distribution == "RedHat" and ansible_distribution_major_version == '7' and ansible_kernel == "3.*"
