---
- hosts: all
  become: true
  become_user: root
  tasks:
  - name: whenever required restart the below services
    copy: 
     src: /etc/ansible/ansible.cfg
     dest: /home/ec2-user
    notify:
    - restart my service
  handlers:
    - name: restart my service
      set_fact:
        myservice_restart: true
