---
- hosts: all
  become: true
  become_user: root
  tasks:
  - name: Install mariadb server
    yum:
     name: mariadb-server
     state: latest
     with_items: "{{ ansible_mount }}"
     when: item.mount == "/" and item.size_available> 300000000
