- hosts: all
  become: true
  tasks:
    - name: remove apache2
      apt: name=apache2 state=absent
      when: ansible_os_family == "Ubuntu" 	  

    - name: remove httpd
      yum: name=httpd state=absent
      when: ansible_os_family == "RedHat" 
