---
- hosts: all
  become: true
  become_user: root
  tasks:
  - name: create user and group
    user:
     name: "{{ item.name }}"
     groups: "{{ item.groups }}"
     state: present
    with_items:
      - { name: 'testuser', groups: 'staff' }
     # - { name: testuser2, groups: it }
