---
- hosts: all
  become: true
  become_method: sudo
  become_user: root
  tasks:
  - name: add several users
    user:
     name: "{{ item }}"
     groups: "wheel"
     state: present
    with_items:
     - testuser1
     - testuser2
