---
- hosts: all
  become: true
  become_user: root
  vars:
   mail_service:
    - postfix
    - dovecot
  tasks:
  - name: Install all mail services
    yum:
     name: "{{ item }}"
     state: latest
    with_items: "{{ mail_service }}" 
